version: "3"
services: 

    react-app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/frontend/node_modules
            - .:/app/frontend                 
        ports: 
            - "3000:3000"